# AprilTag 3 code parameters
# Find descriptions in apriltag/include/apriltag.h:struct apriltag_detector
#                      apriltag/include/apriltag.h:struct apriltag_family

tag_family:        'tagStandard41h12'
tag_threads:       2
tag_decimate:      1.0 
tag_blur:          0.0 
tag_refine_edges:  1 
tag_debug:         0 
publish_tf:        true

