# # Definitions of tags to detect
#
# ## General remarks
#
# - All length in meters
# - Ellipsis (...) signifies that the previous element can be repeated multiple times.
#
# ## Standalone tag definitions
# ### Remarks
#
# - name is optional
#
# ### Syntax
#
# standalone_tags:
#   [
#     {id: ID, size: SIZE, name: NAME},
#     ...
#   ]
standalone_tags:
  [
    {id: 1, size: 0.05, name: tag_1},
    {id: 2, size: 0.05, name: tag_2},
    {id: 3, size: 0.05, name: tag_3},
    {id: 4, size: 0.05, name: tag_4},
    {id: 5, size: 0.01, name: tag_5}
  ]
# ## Tag bundle definitions
# ### Remarks
#
# - name is optional
# - x, y, z have default values of 0 thus they are optional
# - qw has default value of 1 and qx, qy, qz have default values of 0 thus they are optional
#
# ### Syntax
#
# tag_bundles:
#   [
#     {
#       name: 'CUSTOM_BUNDLE_NAME',
#       layout:
#         [
#           {id: ID, size: SIZE, x: X_POS, y: Y_POS, z: Z_POS, qw: QUAT_W_VAL, qx: QUAT_X_VAL, qy: QUAT_Y_VAL, qz: QUAT_Z_VAL},
#           ...
#         ]
#     },
#     ...
#   ]
tag_bundles:
  [

    {
      name: 'first_bundle',
      layout:
        [
          {id: 1, size: 0.05, x: 0, y: 0, z: 0, qx: 0, qy: 0, qz: 0, qw: 1},
          {id: 2, size: 0.05, x: 0.222308, y: 0.0113161, z: -0.00592893, qx: 0.0082829, qy: 0.00790686, qz: -0.0813327, qw: 0.996621},
          {id: 3, size: 0.05, x: 0.563245, y: -0.10427, z: -0.00291549, qx: -0.0054051, qy: 0.00509536, qz: -0.122493, qw: 0.992442},
        ]
    }



    # {
    # name: 'first_bundle',
    # layout:
    #   [
    #     {id: 1, size: 0.05},
    #     {id: 2, size: 0.05},
    #     {id: 3, size: 0.05},
    #   ]
    # },
    # {
    # name: 'bundle_2',
    # layout:
    #   [
    #     {id: 3, size: 0.05},
    #     {id: 5, size: 0.01, x: 0.27}
    #   ]
    # }
  ]
