# # Definitions of tags to detect
#
# ## General remarks
#
# - All length in meters
# - Ellipsis (...) signifies that the previous element can be repeated multiple times.
#
# ## Standalone tag definitions
# ### Remarks
#
# - name is optional
#
# ### Syntax
#
# standalone_tags:
#   [
#     {id: ID, size: SIZE, name: NAME},
#     ...
#   ]
standalone_tags:
  [
    {id: 1, size: 0.05, name: tag_1},
    {id: 2, size: 0.05, name: tag_2},
    {id: 3, size: 0.05, name: tag_3},
    {id: 4, size: 0.05, name: tag_4},
    {id: 5, size: 0.01, name: tag_5}
  ]
# ## Tag bundle definitions
# ### Remarks
#
# - name is optional
# - x, y, z have default values of 0 thus they are optional
# - qw has default value of 1 and qx, qy, qz have default values of 0 thus they are optional
#
# ### Syntax
#
# tag_bundles:
#   [
#     {
#       name: 'CUSTOM_BUNDLE_NAME',
#       layout:
#         [
#           {id: ID, size: SIZE, x: X_POS, y: Y_POS, z: Z_POS, qw: QUAT_W_VAL, qx: QUAT_X_VAL, qy: QUAT_Y_VAL, qz: QUAT_Z_VAL},
#           ...
#         ]
#     },
#     ...
#   ]
tag_bundles:
  [
    #   {
    #   name: 'first_bundle',
    #   layout:
    #     [
    #       {id: 1, size: 0.05, x: 0, y: 0, z: 0, qx: 0, qy: 0, qz: 0, qw: 1},
    #       {id: 3, size: 0.05, x: 1.13419, y: -0.199191, z: -0.0264148, qx: -0.0089956, qy: 0.0209892, qz: -0.11422, qw: 0.993193},
    #       {id: 2, size: 0.05, x: 0.447959, y: 0.0182235, z: -0.00710519, qx: 0.00546285, qy: 0.0153613, qz: -0.0774389, qw: 0.996864},
    #     ]
    # }





    {
    name: 'first_bundle',
    layout:
      [
        {id: 1, size: 0.05},
        {id: 2, size: 0.05},
        # {id: 3, size: 0.05},
      ]
    },
    # {
    # name: 'bundle_2',
    # layout:
    #   [
    #     {id: 3, size: 0.05},
    #     {id: 5, size: 0.01, x: 0.27}
    #   ]
    # }
  ]
